vendor:
    name:       hiqdev
    title:      HiQDev
    github:     https://github.com/hiqdev
    homepage:   http://hiqdev.com/
    forum:      http://forum.hiqdev.com/
    email:      support@hiqdev.com
    authors:
        ottoson:
            name:       Artem Ottoson
            email:      mtema80@gmail.com
            homepage:   http://artemottoson.com/
        hiqsol:
            name:       Andrii Vasyliev
            email:      sol@hiqdev.com
            github:     https://github.com/hiqsol
            homepage:   http://hipanel.com/

package:
    type:           library
    name:           payment-icons
    namespace:      hiqdev\paymenticons
    headline:       Payment Icons
    title:          Set of icons for payment systems and methods
    license:        MIT
    keywords:       payment, icons, merchant, assets, yii2
    description:    |
        Provides:
        - PNG icons in 4 sizes: 60x38, 120x75, 240x150, 480x300
        - available as Bower, NPM and Composer packages
        - [Yii2](http://yiiframework.com) assets bundle
        - else?

readme:
    sections:
        - Acknowledgements
        - Installation
        - Example
        - License

require:
    hiqdev/hidev-php:    "*"
